### ISSUE TITLE
How to decode KrbApReq to base64 for inclusion into HTTP header?

### ISSUE THREAD

**Issue by undecided2013** [SteveSyfuhs/Kerberos.NET#127]
It's unclear of how to get a base64 string of the KrbApReq ticket returned by GetServiceTicket api.
I would think this is a common use case for this api but I skimmed through the code and got quite lost looking for the way to decode the ticket to base64

**Comment by SteveSyfuhs** [comment]
It probably wouldn't hurt to add some methods to wrap all this. The trick is that it's usually not just kerberos in the header, but kerberos wrapped in GSS, wrapped in SPNego, and callers need to be able to distinguish between that and a regular kerberos ticket.

In any case, you'd do something like
```
var apReq = await client.GetServiceTicket(...);
var ticketForHeader = Convert.ToBase64String(apReq.EncodeGssApi()); // or if you want _just_ kerb you call .EncodeApplication()
```

The `GetServiceTicket` method is overloaded so it can return either a session context or a ticket directly.

**Comment by undecided2013** [comment]
Thanks Steve, it seems that the GssApi return the type of token needed but I have not been able to get it to work with the Kerberos secured REST service I am trying to access. Java guys and Node guys using the MIT library have no problem making it work.

**Comment by SteveSyfuhs** [comment]
What error is the service returning?

**Comment by undecided2013** [comment]
401

**Comment by SteveSyfuhs** [comment]
Can you compare a working ticket with a failing ticket? It's difficult to determine why a server wouldn't accept it just by a 401 error.

**Comment by undecided2013** [comment]
Yeah. They all look like Base64 to me. They start with 'YII' which seems like the correct base65 encoding for the kerberos tickets, the 1st 3 characters match what the java/node guys create.

**Comment by SteveSyfuhs** [comment]
There's a tool under the root of this project called KerbDumpCore that will parse the tickets: https://github.com/SteveSyfuhs/Kerberos.NET/tree/master/KerbDumpCore

**Comment by undecided2013** [comment]
Cool, trying that but it throws an exception:
System.Security.SecurityException: Invalid Checksum
   at Kerberos.NET.Crypto.RC4Transformer.Decrypt(ReadOnlyMemory`1 ciphertext, KerberosKey key, KeyUsage usage) in C:\dev\Kerberos.NET-master\Kerberos.NET\Crypto\RC4\RC4Transformer.cs:line 77
   at Kerberos.NET.Entities.KrbEncryptedData.Decrypt[T](KerberosKey key, KeyUsage usage, Func`2 func) in C:\dev\Kerberos.NET-master\Kerberos.NET\Entities\Krb\KrbEncryptedData.cs:line 12
   at Kerberos.NET.Crypto.DecryptedKrbApReq.Decrypt(KerberosKey key) in C:\dev\Kerberos.NET-master\Kerberos.NET\Crypto\DecryptedKrbApReq.cs:line 63
   at Kerberos.NET.Crypto.DecryptedKrbApReq.Decrypt(KeyTable keytab) in C:\dev\Kerberos.NET-master\Kerberos.NET\Crypto\DecryptedKrbApReq.cs:line 58
   at Kerberos.NET.Entities.ContextToken.DecryptApReq(KrbApReq token, KeyTable keytab) in C:\dev\Kerberos.NET-master\Kerberos.NET\Entities\SpNego\ContextToken.cs:line 30
   at Kerberos.NET.Entities.KerberosContextToken.DecryptApReq(KeyTable keys) in C:\dev\Kerberos.NET-master\Kerberos.NET\Entities\SpNego\KerberosContextToken.cs:line 21
   at Kerberos.NET.Entities.NegotiateContextToken.DecryptApReq(KeyTable keys) in C:\dev\Kerberos.NET-master\Kerberos.NET\Entities\SpNego\NegotiateContextToken.cs:line 31
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes) in C:\dev\Kerberos.NET-master\Kerberos.NET\KerberosValidator.cs:line 54
   at KerbDump.Form1.Decode(String ticket, KeyTable key) in C:\dev\Kerberos.NET-master\KerbDump\Form1.cs:line 253
   at KerbDump.Form1.Decode() in C:\dev\Kerberos.NET-master\KerbDump\Form1.cs:line 129



I am copying the base64 gssapi string into the EncodedTicket field,
Under Key I am putting the user password
Under Host I am putting the SPN and then I click 'Decode'

**Comment by SteveSyfuhs** [comment]
The key would be the service account key, not the user key. Service tickets are encrypted by the KDC using the service account password. If you leave the key field blank it'll decode up to the decryption step and provides some useful metadata.

**Comment by undecided2013** [comment]
All the other values are right? And, base64 is ok to paste into Encoded Ticket?

**Comment by SteveSyfuhs** [comment]
Yes. If a key isn't present it just decodes the base64 as-is. If a key is present it'll attempt to decrypt the ticket with the key. If a host is present it'll use that as an input of the decryption if it happens to be using AES.

**Comment by undecided2013** [comment]
I am getting System.Security.SecurityException: Invalid Checksum
   at Kerberos.NET.Crypto.RC4Transformer.Decrypt(ReadOnlyMemory`1 ciphertext, KerberosKey key, KeyUsage usage) in C:\dev\Kerberos.NET-master\Kerberos.NET\Crypto\RC4\RC4Transformer.cs:line 77


both for the working tickets and non-working tickets....

**Comment by SteveSyfuhs** [comment]
Did you load a keytab? Try closing and reopening the app.
