### ISSUE TITLE
Invalid checksum 

### ISSUE THREAD

**Issue by InnovationZone** [SteveSyfuhs/Kerberos.NET#18]
Hi,

I've followed all the great samples provided and actually I'm facing the following issue:

`Invalid checksum     at Kerberos.NET.Crypto.AES.AESDecryptor.DecryptWith(Byte[] workBuffer, Int32[] workLens, Byte[] key, Byte[] iv, KeyUsage usage)
   at Kerberos.NET.Crypto.AES.AESDecryptor.Decrypt(Byte[] cipher, Byte[] key, Byte[] iv, KeyUsage usage)
   at Kerberos.NET.Crypto.AES.AESDecryptor.Decrypt(Byte[] cipher, KerberosKey key, KeyUsage usage)
   at Kerberos.NET.Crypto.AESDecryptedData.Decrypt(KeyTable keytab)
   at Kerberos.NET.KerberosRequest.Decrypt(KrbApReq token, KeyTable keytab)
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes)
   at Kerberos.NET.KerberosAuthenticator.Authenticate(Byte[] token)
   at Kerberos.NET.KerberosAuthenticator.Authenticate(String token)
   at elearningapp.MessageHandlers.KerberosMiddleware.ParseKerberosHeader(OwinEnvironment env, HttpContext httpContext)`

Does anyone has already encountered that before ? 

Thansk in advance !

**Comment by SteveSyfuhs** [comment]
This often indicates either the provided key isn’t correct, or the SPN doesn’t match. AES explicitly requires an SPN be set on the provided KerberosKey if you are providing a raw secret. You don't need to provide the SPN if you're using a key tab file.

**Comment by SteveSyfuhs** [comment]
Possibly. Depends on how the file was created. You can try reviewing the contents of the file (using the debugger or some external tool) and see what the PrincipalName is and make sure it matches the SPN on the service account in AD.

You can also try disabling AES on the service account in AD so it forces RC4 to make sure the key itself is correct.
