### ISSUE TITLE
authenticate trouble

### ISSUE THREAD

**Issue by Zhukbo** [SteveSyfuhs/Kerberos.NET#222]
Hi, Steve. I'm trying to authenticate user using Kerberos (I set up Active Directory and DNS Server on Windows Server 2008 R2, in the role of the client I used a Windows 10).
I used your example but i have a trouble.
In English - The return from the operation was due to a timeout
![изображение](https://user-images.githubusercontent.com/35612327/115306560-afa27200-a170-11eb-9c73-5a935a36508f.png)
What could be the problem?
Thanks in advance.

**Comment by SteveSyfuhs** [comment]
Can you share the stacktrace for the full exception?

**Comment by Zhukbo** [comment]
Sure.
![изображение](https://user-images.githubusercontent.com/35612327/115366543-19049e00-a1ce-11eb-9515-9e755976c822.png)
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=Возврат из операции произошел из-за превышения времени ожидания
  Source=Kerberos.NET
  StackTrace:
   at Kerberos.NET.Dns.DnsQueryWin32.QuerySrvRecord(String query, DnsRecordType type, DnsQueryOptions options) in D:\a\1\s\Kerberos.NET\Dns\DnsQueryWin32.cs:line 75
   at Kerberos.NET.Dns.WindowsDnsQuery.Query(String query, DnsRecordType type) in D:\a\1\s\Kerberos.NET\Dns\WindowsDnsQuery.cs:line 23
   at Kerberos.NET.Dns.DnsQuery.<QuerySrv>d__7.MoveNext() in D:\a\1\s\Kerberos.NET\Dns\DnsQuery.cs:line 59
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.ClientDomainService.<QueryDns>d__23.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\ClientDomainService.cs:line 162
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.ClientDomainService.<Query>d__22.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\ClientDomainService.cs:line 129
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.ClientDomainService.<LocateKdc>d__18.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\ClientDomainService.cs:line 58
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.KerberosTransportBase.<LocatePreferredKdc>d__47.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\KerberosTransportBase.cs:line 120
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.TcpKerberosTransport.<GetClient>d__12.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 77
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.TcpKerberosTransport.<SendMessage>d__11`1.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 68
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Transport.KerberosTransportSelector.<SendMessage>d__6`1.MoveNext() in D:\a\1\s\Kerberos.NET\Client\Transport\KerberosTransportSelector.cs:line 90
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Client.KerberosClient.<RequestTgt>d__89.MoveNext() in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 1009
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Client.KerberosClient.<AuthenticateCredential>d__71.MoveNext() in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 345
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.Client.KerberosClient.<Authenticate>d__70.MoveNext() in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 328
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Kerb4_6_1.Program.<Auth>d__1.MoveNext() in C:\Users\bogda\source\repos\Kerb4_6_1\Kerb4_6_1\Program.cs:line 32

  This exception was originally thrown at this call stack:
    Kerberos.NET.Dns.DnsQueryWin32.QuerySrvRecord(string, Kerberos.NET.Dns.DnsRecordType, Kerberos.NET.Dns.DnsQueryOptions) in DnsQueryWin32.cs
    Kerberos.NET.Dns.WindowsDnsQuery.Query(string, Kerberos.NET.Dns.DnsRecordType) in WindowsDnsQuery.cs
    Kerberos.NET.Dns.DnsQuery.QuerySrv(string) in DnsQuery.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Kerberos.NET.Transport.ClientDomainService.QueryDns(string, string, System.Collections.Generic.List<Kerberos.NET.Dns.DnsRecord>) in ClientDomainService.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Kerberos.NET.Transport.ClientDomainService.Query(string, string) in ClientDomainService.cs
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]

**Comment by Zhukbo** [comment]
But if i run this code on Windows Server 2008 R2 I will receive it
            


var client = new KerberosClient();

            var kerbCred = new KerberosPasswordCredential("user2@POLIK.UA", "P@ssw0rd");

            await client.Authenticate(kerbCred);

            var ticket = await client.GetServiceTicket("HOST/bogdan-server.polik.ua");

            var header = "Negotiate " + Convert.ToBase64String(ticket.EncodeGssApi().ToArray());


            Console.WriteLine("client " + client);
            Console.WriteLine("Kerberos Credentials " + kerbCred);
            Console.WriteLine("ticket " + ticket);
            Console.WriteLine("Header " + header);`
![изображение](https://user-images.githubusercontent.com/35612327/115378208-f9bf3e00-a1d8-11eb-8106-35a1812aabea.png)

**Comment by SteveSyfuhs** [comment]
So running the code on Windows 10 returns a timeout exception when querying for DNS, and when running from Server 2008 R2 it works just fine? It's a bit strange that DNS is timing out, as that's highly irregular for DNS operations. Can you confirm your Windows 10 DNS is configured correctly and pointing to a proper DNS server?

**Comment by Zhukbo** [comment]
I have already fixed the error, it was because Windows Server 2008 R2 was running on virtual machine (VMware) on windows 10. And I have a question: does your library have a method that will show lifetime for user ticket on the client side? Thanks in advance.

**Comment by SteveSyfuhs** [comment]
It's a bit difficult to do so at the moment. You can get it by pulling the ticket entry out of the cache and decrypting the encrypted part.

**Comment by Zhukbo** [comment]
Thanks

**Comment by Zhukbo** [comment]
If I understood correctly, it is necessary to use this cache, but by what method to receive it? 
![изображение](https://user-images.githubusercontent.com/35612327/117576602-35ba3480-b0ef-11eb-9112-e001fa5a7342.png)

![изображение](https://user-images.githubusercontent.com/35612327/117576532-01467880-b0ef-11eb-8288-0af3000e054a.png)
