### ISSUE TITLE
Getting KDC KDC_ERR_S_PRINCIPAL_UNKNOWN: Server not found in Kerberos database error

### ISSUE THREAD

**Issue by knchachad** [SteveSyfuhs/Kerberos.NET#321]
We are getting the below error while connecting to Oracle Database using .net Core 3.1 via Kerberos authentication. Our application is running as a Windows service on Windows server 2019 Standard v1809.
Can you please let us the know the exact reason of error?

Kerberos.NET.KerberosProtocolException: KDC KDC_ERR_S_PRINCIPAL_UNKNOWN: Server not found in Kerberos database
   at Kerberos.NET.Client.LsaCredentialCache.GetCacheItem(String key, String container) in D:\a\1\s\Kerberos.NET\Client\LsaCredentialCache.cs:line 105
   at Kerberos.NET.Client.LsaCredentialCache.GetCacheItem[T](String key, String container) in D:\a\1\s\Kerberos.NET\Client\LsaCredentialCache.cs:line 125
   at Kerberos.NET.Client.KerberosClient.GetServiceTicket(RequestServiceTicket rst, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 575
   at OracleInternal.Network.AnoKerberos.Authenticate(String KRB5Conf, String KRB5CCName, String SN, String Host, Byte[]& kkey)
   at OracleInternal.Network.Ano.KerberosHandshake(AuthenticationService AS, String KRB5Conf, String KRB5CCName)
   at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
   at OracleInternal.Network.OracleCommunication.Connect(String tnsDescriptor, Boolean doNAHandshake, String IName, ConnectionOption CO)
   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)

**Comment by SteveSyfuhs** [comment]
The error is pretty specific.

> KDC KDC_ERR_S_PRINCIPAL_UNKNOWN: Server not found in Kerberos database

That means you used an SPN that isn't registered on any service account.
________________________________
From: knchachad ***@***.***>
Sent: Tuesday, October 18, 2022 8:32:40 AM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] Getting KDC KDC_ERR_S_PRINCIPAL_UNKNOWN: Server not found in Kerberos database error (Issue #321)


We are getting the below error while connecting to Oracle Database using .net Core 3.1 via Kerberos authentication. Our application is running as a Windows service on Windows server 2019 Standard v1809.
Can you please let us the know the exact reason of error?

Kerberos.NET.KerberosProtocolException: KDC KDC_ERR_S_PRINCIPAL_UNKNOWN: Server not found in Kerberos database
at Kerberos.NET.Client.LsaCredentialCache.GetCacheItem(String key, String container) in D:\a\1\s\Kerberos.NET\Client\LsaCredentialCache.cs:line 105
at Kerberos.NET.Client.LsaCredentialCache.GetCacheItem[T](String key, String container) in D:\a\1\s\Kerberos.NET\Client\LsaCredentialCache.cs:line 125
at Kerberos.NET.Client.KerberosClient.GetServiceTicket(RequestServiceTicket rst, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 575
at OracleInternal.Network.AnoKerberos.Authenticate(String KRB5Conf, String KRB5CCName, String SN, String Host, Byte[]& kkey)
at OracleInternal.Network.Ano.KerberosHandshake(AuthenticationService AS, String KRB5Conf, String KRB5CCName)
at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
at OracleInternal.Network.OracleCommunication.Connect(String tnsDescriptor, Boolean doNAHandshake, String IName, ConnectionOption CO)
at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)

**Comment by knchachad** [comment]
Hi Steve,
I checked the SPN for the service account by running the setspn command. SPN is present for it. Also, tried a running a Sample application using .Net framework 4.6.1. It is able to connect to the Oracle database with same ID. Once it connects, .net core application also runs for 15-20 mins on the same server. After 15-20 mins, again we get same error. Any idea why it works with .net framework and not with .net core?

**Comment by SteveSyfuhs** [comment]
Presumably Oracle is using a different library for 4.6.1. The callstack provided doesn't manipulate the SPN in any way. It's just passing it down all the way to the Windows SSPI interface. Based on the use of `LsaCredentialCache`, this is in a special mode of just-let-Windows-figure-it-out. Kerberos.NET isn't really in play at all in this mode and is just acting as a lightweight API over Windows. Given that, the only thing that would suggest a change between the 20 minutes is the SPN being passed. You would need to investigate what the Oracle part of the library is passing.

**Comment by knchachad** [comment]
Hi Steve,
I tried logging the SPN passed to the method LsaInterop.GetTicket. Same SPN is being passed every time- in case of success and failure. So, the Win32 library is giving different result. I tried removing the catch block and throwing the original Win32 exception. It says "System.ComponentModel.Win32Exception: The security database on the server does not have a computer account for this workstation trust relationship." What could be the reason for this?

**Comment by SteveSyfuhs** [comment]
> The security database on the server does not have a computer account for this workstation trust relationship.

It's actually the same literal error on the wire as `KDC_ERR_S_PRINCIPAL_UNKNOWN`. That is just how Windows reports it. That's why it's translated back to the more specific Kerb error.

https://github.com/dotnet/Kerberos.NET/blob/bcd93a3444b5ab4968fd564564c79c96c090cf66/Kerberos.NET/Client/LsaCredentialCache.cs#L103-L106

The security database = Active Directory
on the server = your DC
does not have a computer account = not found
for this workstation trust relationship = your computer is asking

So, Oracle is asking Kerberos.NET to get a ticket to SPN. Kerberos.NET is asking Windows. Windows is failing to retrieve it because the SPN can't be found. I don't know why Windows would have that issue in this particular case.

**Comment by knchachad** [comment]
Hi Steve,
We have observed that the .net core application runs fine even after 15 mins on another server which has Windows Server 2016 standard. Our server has Windows Server 2019 standard where this issue is observed. Is there any known difference between the 2 windows versions that may be causing this issue?

**Comment by SteveSyfuhs** [comment]
> Is there any known difference between the 2 windows versions that may be causing this issue?

I wouldn't even know where to begin with that unfortunately. There are any number of differences between the OSes. That is a question that would need to be escalated through MS Support teams with a repro.
